package main

import (
	_ "embed"
	"fmt"
	"log"
	"net/netip"
	"os"
	"path"
	"strings"
	"text/template"
)

var configs = []Sensor{
	{MAC: "F0:24:F9:97:C2:98", IpAddress: "10.0.64.10", Name: "vault"},
	{MAC: "F0:24:F9:97:B8:40", IpAddress: "10.0.64.11", Name: "storage"},
	{MAC: "F0:24:F9:9A:65:1C", IpAddress: "10.0.64.12", Name: "boycave"},
	{MAC: "F0:24:F9:99:68:04", IpAddress: "10.0.64.13", Name: "theater"},
	{MAC: "f0:24:f9:99:68:00", IpAddress: "10.0.64.14", Name: "flex"},
	{MAC: "F0:24:F9:9A:66:4C", IpAddress: "10.0.64.15", Name: "bath-5"},
	{MAC: "F0:24:F9:97:D0:50", IpAddress: "10.0.64.16", Name: "exercise"},
	{MAC: "10:06:1C:17:37:A8", IpAddress: "10.0.64.17", Name: "mechanical"},
	{MAC: "F0:24:F9:97:BD:A8", IpAddress: "10.0.64.18", Name: "linen", NoCO2: true},
	{MAC: "F0:24:F9:97:D6:E4", IpAddress: "10.0.64.19", Name: "lavatory-2"},
	{MAC: "10:06:1C:18:D5:E8", IpAddress: "10.0.64.20", Name: "lower-stairwell"},
	{MAC: "F0:24:F9:97:BE:98", IpAddress: "10.0.64.21", Name: "garage-ne"},
	{MAC: "F0:24:F9:9A:64:64", IpAddress: "10.0.64.22", Name: "garage-se", NoCO2: true},
	{MAC: "F0:24:F9:97:D7:64", IpAddress: "10.0.64.23", Name: "everything"},
	{MAC: "F0:24:F9:9A:66:28", IpAddress: "10.0.64.24", Name: "kitchen"},
	{MAC: "F0:24:F9:97:B8:24", IpAddress: "10.0.64.25", Name: "livingroom-west"},
	{MAC: "F0:24:F9:9A:E9:24", IpAddress: "10.0.64.26", Name: "master-bedroom"},
	{MAC: "F0:24:F9:9A:EA:EC", IpAddress: "10.0.64.27", Name: "master-bathroom", NoCO2: true},
	{MAC: "F0:24:F9:97:D6:84", IpAddress: "10.0.64.28", Name: "master-shower", NoCO2: true},
	{MAC: "F0:24:F9:97:BF:B0", IpAddress: "10.0.64.29", Name: "master-closet"},
	{MAC: "F0:24:F9:9A:EA:84", IpAddress: "10.0.64.30", Name: "lavatory"},
	{MAC: "F0:24:F9:97:C1:F8", IpAddress: "10.0.64.31", Name: "bath-2"},
	{MAC: "F0:24:F9:9A:EC:E8", IpAddress: "10.0.64.32", Name: "guest-bedroom"},
	{MAC: "F0:24:F9:9A:EE:4C", IpAddress: "10.0.64.33", Name: "livingroom-east"},
	{MAC: "F0:24:F9:97:D1:78", IpAddress: "10.0.64.34", Name: "mid-stairwell"},
	{MAC: "F0:24:F9:97:BC:28", IpAddress: "10.0.64.35", Name: "bath-3"},
	{MAC: "F0:24:F9:97:D1:BC", IpAddress: "10.0.64.36", Name: "ethan"},
	{MAC: "F0:24:F9:9A:ED:10", IpAddress: "10.0.64.37", Name: "crafts"},
	{MAC: "F0:24:F9:97:D0:04", IpAddress: "10.0.64.38", Name: "aaron"},
	{MAC: "F0:24:F9:95:20:AC", IpAddress: "10.0.64.39", Name: "bath-4"},
	{MAC: "F0:24:F9:99:6A:54", IpAddress: "10.0.64.40", Name: "upper-stairwell", NoCO2: true},
}

type Sensor struct {
	Name      string
	MAC       string
	IpAddress string
	// NoCO2 marks a node that was built without an SCD4x fitted. The template
	// omits the CO2 sensor entirely for these -- otherwise ESPHome marks the
	// missing chip failed on every boot and the recovery watchdog burns its
	// whole reboot budget hunting for hardware that was never there.
	// Confirmed by i2c bus scan: these nodes show only 0x44 (SHT4x), no 0x62.
	NoCO2   bool
	Secrets Secrets
}

type Secrets struct {
	EspAPIKey    string
	OtaPassword  string
	WifiSSID     string
	WifiPassword string
}

//go:embed template.yaml
var espHomeTemplate string

// DNS output contract with infra-configs.
//
// The iot.joyner.ws and 64.0.10.in-addr.arpa zones are owned and hand-maintained
// in infra-configs (alfred/bind9/db.iot.joyner.ws and db.64.0.10): they hold the
// SOA/serial, the NS record and the hand-managed IoT devices, and each one
// $INCLUDEs a records-only fragment written here:
//
//	db.iot.joyner.ws.sensors -> /etc/bind/db.iot.joyner.ws.sensors (A records)
//	db.64.0.10.sensors       -> /etc/bind/db.64.0.10.sensors       (PTR records)
//
// Everything this generator emits must therefore stay inside the sensor block,
// matching the comment beside those $INCLUDE lines:
//
//	addresses: 10.0.64.10 - 10.0.64.99  (sensorFirst..sensorLast below)
//	names:     <node>.temphum.iot.joyner.ws.
//
// 10.0.64.100 - 10.0.64.199 is reserved for hand-maintained devices (names
// directly under iot.joyner.ws, reservations in alfred/dhcp/dhcpd.conf), and
// 10.0.72.0/24 is the dynamic pool. The fragments carry no SOA, $ORIGIN or
// serial: they inherit the including zone's origin, so forward names are
// written fully qualified and PTR owners as the bare last octet.
//
// After regenerating, copy both fragments into infra-configs/alfred/bind9/,
// bump the serial in BOTH hand-maintained zone files, and deploy bind9.
var (
	sensorFirst = netip.MustParseAddr("10.0.64.10")
	sensorLast  = netip.MustParseAddr("10.0.64.99")
)

const fragmentHeader = "; GENERATED by environmental-sensors (main.go) -- do not edit by hand.\n" +
	"; Records-only fragment $INCLUDEd by the hand-maintained zone in infra-configs;\n" +
	"; sensor block only: 10.0.64.10-10.0.64.99, <node>.temphum.iot.joyner.ws.\n"

// sensorAddr parses a sensor's address and refuses anything outside the sensor
// block, so the generator can never collide with hand-maintained IoT devices.
func sensorAddr(s Sensor) netip.Addr {
	a, err := netip.ParseAddr(s.IpAddress)
	if err != nil {
		log.Fatalf("%s: bad IpAddress %q: %v", s.Name, s.IpAddress, err)
	}
	if a.Compare(sensorFirst) < 0 || a.Compare(sensorLast) > 0 {
		log.Fatalf("%s: %s is outside the sensor block %s-%s (see the DNS output contract)", s.Name, a, sensorFirst, sensorLast)
	}
	return a
}

func main() {
	// Validate every sensor before writing anything, so a bad entry can't leave
	// half-written fragments behind for someone to copy into infra-configs.
	for _, s := range configs {
		sensorAddr(s)
	}

	// instantiate ESPHome template
	var espTmpl = template.Must(template.New("espconf").Parse(espHomeTemplate))

	// create UniFi DHCP lease CSV
	leasesFileHandle, err := os.Create("unifi-dhcp.csv")
	if err != nil {
		log.Fatal(err)
	}
	defer leasesFileHandle.Close()

	// create ISC DHCP lease config
	dhcpdconfFileHandle, err := os.Create("dhcpd-iot.conf")
	if err != nil {
		log.Fatal(err)
	}
	defer dhcpdconfFileHandle.Close()

	// create the records-only DNS fragments (see "DNS output contract" above)
	aRecordFileHandle, err := os.Create("db.iot.joyner.ws.sensors")
	if err != nil {
		log.Fatal(err)
	}
	defer aRecordFileHandle.Close()
	PTRFileHandle, err := os.Create("db.64.0.10.sensors")
	if err != nil {
		log.Fatal(err)
	}
	defer PTRFileHandle.Close()
	for _, fh := range []*os.File{aRecordFileHandle, PTRFileHandle} {
		if _, err := fh.WriteString(fragmentHeader); err != nil {
			log.Fatal(err)
		}
	}

	for _, dc := range configs {
		dc.Secrets = secrets
		addr := sensorAddr(dc)

		// write config file
		filename := fmt.Sprintf("%s.yaml", dc.Name)
		err := os.MkdirAll("configs", 0700)
		if err != nil {
			log.Fatal(err)
		}
		f, err := os.Create(path.Join("configs", filename))
		if err != nil {
			log.Fatal(err)
		}
		defer f.Close()

		// write config for device
		err = espTmpl.Execute(f, dc)
		if err != nil {
			log.Fatal("interpreting config: ", err)
		}
		// append to the DNS fragments
		dnsName := fmt.Sprintf("%s.temphum.iot.joyner.ws.", dc.Name)
		entry := fmt.Sprintf("%s\tA\t%s\n", dnsName, addr)
		aRecordFileHandle.Write([]byte(entry))
		// PTR owner is the bare last octet, relative to the including
		// zone's 64.0.10.in-addr.arpa. origin.
		entry = fmt.Sprintf("%d\tPTR\t%s\n", addr.As4()[3], dnsName)
		PTRFileHandle.Write([]byte(entry))

		if strings.Contains(dc.MAC, "xx:xx") {
			continue
		}
		// append to leases file
		entry = fmt.Sprintf("%s,%s,%s,,,,\n", dc.MAC, dc.IpAddress, dc.Name)
		leasesFileHandle.Write([]byte(entry))

		// append to leases file
		entry = fmt.Sprintf("host %s { hardware ethernet %s; fixed-address %s; }\n", dc.Name, dc.MAC, dc.IpAddress)
		dhcpdconfFileHandle.Write([]byte(entry))

	}
}
