esphome:
  name: "{{.Name}}"
  # Ensure i2c power is turned on early
  on_boot:
    - priority: 600
      then:
        - switch.turn_on: i2c_power

esp32:
  board: adafruit_feather_esp32_v2
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "{{.Secrets.EspAPIKey}}"

ota:
  - platform: esphome
    password: "{{.Secrets.OtaPassword}}"

wifi:
  ssid: "{{.Secrets.WifiSSID}}"
  password: "{{.Secrets.WifiPassword}}"
  fast_connect: true

i2c:
  sda: SDA
  scl: SCL
  scan: true
  id: bus_a

# Power enable for STEMMA QT
output:
  - platform: gpio
    pin:
      number: 2   # GPIO 2 for Feather ESP32 v2
      inverted: false
    id: i2c_power_out

switch:
  - platform: output
    name: "STEMMA I2C Power"
    output: i2c_power_out
    id: i2c_power

sensor:
  - platform: scd4x
    co2:
      name: "scd4x CO2"
    temperature:
      name: "scd4x Temperature"
    humidity:
      name: "scd4x Humidity"
    update_interval: 30s

  - platform: sht4x
    temperature:
      name: "sht4x Temperature"
    humidity:
      name: "sht4x Relative Humidity"

web_server:
  port: 80

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 20

light:
  - platform: esp32_rmt_led_strip  # New component
    pin: 0
    num_leds: 1
    rgb_order: GRB
    chipset: WS2812
    use_psram: false
    name: "NeoPixel"
    id: "neopixel"
    initial_state:
      state: false
      red: 0.0
      green: 0.1
      blue: 0.0

  - platform: status_led
    name: "Status Light"
    pin: GPIO13
    initial_state:
      state: true
